[MonD]
SkinName=catppuccin
Author=modkavartini
Version=1.3.1
HeaderImage=#@#\bar.bmp
VariableFiles=#@#inc\var.inc | #@#inc\flavors.inc | #@#inc\snippets.inc
Exclude=#@#pinned
LoadType=Skin
Load=catppuccin\bar\bar.ini
PreviewImage=https://repository-images.githubusercontent.com/662383027/084771df-98aa-4fd0-8741-29572cb8d571
ProfilePicture=https://avatars.githubusercontent.com/u/81793953
Description=a set of skins made using the catppuccin color scheme
