[variables]

1.name=Discord
1.icon=#@#pinned\icons\Discord_lnk.png
1.action=["C:\Users\abhir\Desktop\Discord.lnk"]
2.name=Spotify
2.icon=#@#pinned\icons\Spotify_lnk.png
2.action=["C:\Users\abhir\Desktop\Spotify.lnk"]
3.name=YT Music
3.icon=#@#pinned\icons\YT Music_lnk.png
3.action=["C:\Users\abhir\Desktop\YT Music.lnk"]
4.name=GitHub Desktop
4.icon=#@#pinned\icons\GitHub Desktop_lnk.png
4.action=["C:\Users\abhir\Desktop\GitHub Desktop.lnk"]
